name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Change directory to project root
        run: cd ./studyRoom

      - name: Print current directory
        run: pwd
      
      - name: Install dependencies
        run: npm install

      - name: Lint with ESLint
        run: npm run lint
        continue-on-error: true

      - name: Format with Prettier
        run: npm run format
        continue-on-error: true

      - name: Test if files have been modified
        run: git diff --exit-code
