name: CI

on:
  push:
    branches:
      - main

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout le code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16



      - name: Install dependencies
        run: npm install

      - name: Lint with ESLint
        run: npm run lint

      - name: Format with Prettier
        run: npm run format
